### PR TITLE
Update to LFS 8.2

### PR DESCRIPTION
**Pull request by EvilFreelancer**
Hello @reinterpretcat !
Large update to [new version](http://www.linuxfromscratch.org/lfs/view/stable/) of LFS, packages from this [list](http://www.linuxfromscratch.org/lfs/view/stable/chapter01/whatsnew.html) was updated and added, patch for bash was removed. Order of some packages was changed, for example `check` sript was moved from `prepare` to `build` stage. 
Also need build toolchains, iso and img files, and put new release.
Enjoy :smile:

### CODE REVIEW

**Comment by EvilFreelancer** [comment]
Oops, seems system can not create loop device, i see message what /dev/loop0 is not found, need check.

**Comment by reinterpretcat** [comment]
yeah, has to be checked before merged..

**Comment by EvilFreelancer** [comment]
@reinterpretcat hello! But PR still have a bug with loop device, i've not fixed it yet.

**Comment by reinterpretcat** [comment]
No problem, at the moment LFS 8.1 is release. If people will have questions, I would recommend to use it.

**Pull request merged**
